name: 测试

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    
    - name: 设置Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: 安装uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        
    - name: 安装依赖
      run: |
        uv sync --all-extras
        
    - name: 运行测试
      run: |
        uv run pytest -v
        
    - name: 代码格式检查
      run: |
        uv run ruff check .
        
    - name: 代码格式化检查
      run: |
        uv run ruff format --check .